-- Task 1:
ALTER TABLE PROJEKTY ADD CONSTRAINT PK_PROJEKTY PRIMARY KEY(ID_PROJEKTU);
ALTER TABLE PROJEKTY ADD CONSTRAINT UK_PROJEKTY UNIQUE(OPIS_PROJEKTU);
ALTER TABLE PROJEKTY MODIFY OPIS_PROJEKTU NOT NULL;
ALTER TABLE PROJEKTY ADD CHECK(DATA_ZAKONCZENIA>DATA_ROZPOCZECIA);
ALTER TABLE PROJEKTY ADD CHECK(FUNDUSZ>0 OR FUNDUSZ IS NULL);

SELECT C.CONSTRAINT_NAME, C.CONSTRAINT_TYPE AS C_TYPE, C.SEARCH_CONDITION, CC.COLUMN_NAME FROM USER_CONSTRAINTS C INNER JOIN USER_CONS_COLUMNS CC ON C.CONSTRAINT_NAME=CC.CONSTRAINT_NAME
WHERE C.TABLE_NAME='PROJEKTY' ORDER BY C.CONSTRAINT_NAME;

-- Task 2:
INSERT INTO PROJEKTY VALUES(
    DEFAULT,
    'Indeksy bitmapowe',
    TO_DATE('1999/04/12', 'yyyy/mm/dd'),
    TO_DATE('2001/09/30', 'yyyy/mm/dd'),
    40000
);

-- Task 3:
CREATE TABLE PRZYDZIALY (
    ID_PROJEKTU NUMBER(4) CONSTRAINT  FK_PRZYDZIALY_01 REFERENCES PROJEKTY(ID_PROJEKTU) CHECK(ID_PROJEKTU IS NOT NULL),
    NR_PRACOWNIKA NUMBER(6) CONSTRAINT FK_PRZYDZIALY_02 REFERENCES PRACOWNICY(ID_PRAC) CHECK(NR_PRACOWNIKA IS NOT NULL),
    OD DATE DEFAULT SYSDATE,
    DO DATE,
    CONSTRAINT CHK_PRZYDZIALY_DATY CHECK(DO>OD),
    STAWKA NUMBER(7,2) CONSTRAINT CHK_PRZYDZIALY_STAWKA CHECK(STAWKA>0),
    ROLA VARCHAR2(20) CONSTRAINT CHK_PRZYDZIALY_ROLA CHECK(ROLA IN ('KIERUJĄCY', 'ANALITYK', 'PROGRAMISTA')),
    CONSTRAINT PK_PRZYDZIALY PRIMARY KEY(ID_PROJEKTU, NR_PRACOWNIKA)
);

-- Task 4:
INSERT INTO PRZYDZIALY VALUES (
    (SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU='Indeksy bitmapowe'),
    170,
    TO_DATE('1999/04/10', 'yyyy/mm/dd'),
    TO_DATE('1999/05/10', 'yyyy/mm/dd'),
    1000,
    'KIERUJĄCY'
);

INSERT INTO PRZYDZIALY VALUES (
    (SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU='Indeksy bitmapowe'),
    140,
    TO_DATE('2000/12/01', 'yyyy/mm/dd'),
    NULL,
    1500,
    'ANALITYK'
);

INSERT INTO PRZYDZIALY VALUES (
    (SELECT ID_PROJEKTU FROM PROJEKTY WHERE OPIS_PROJEKTU='Sieci kręgosłupowe'),
    140,
    TO_DATE('2015/08/14', 'yyyy/mm/dd'),
    NULL,
    2500,
    'KIERUJĄCY'
);

-- Task 5:
ALTER TABLE PRZYDZIALY ADD GODZINY NUMBER(4) NOT NULL CHECK(GODZINY<=9999);

-- Task 6:
ALTER TABLE PRZYDZIALY ADD GODZINY NUMBER(4) CHECK(GODZINY<=9999);

UPDATE PRZYDZIALY SET GODZINY = 100;

ALTER TABLE PRZYDZIALY MODIFY GODZINY NOT NULL;

-- Task 7:
ALTER TABLE PROJEKTY DISABLE CONSTRAINT UK_PROJEKTY;

SELECT CONSTRAINT_NAME, STATUS FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME='UK_PROJEKTY';

-- Task 8:
INSERT INTO PROJEKTY VALUES(
    DEFAULT,
    'Indeksy bitmapowe',
    TO_DATE('2015/04/12', 'yyyy/mm/dd'),
    TO_DATE('2016/09/30', 'yyyy/mm/dd'),
    40000
);

SELECT * FROM PROJEKTY;

-- Task 9:
ALTER TABLE PROJEKTY ENABLE CONSTRAINT UK_PROJEKTY;

-- Task 10:
UPDATE PROJEKTY SET OPIS_PROJEKTU='Inne indeksy' WHERE FUNDUSZ=40000;

ALTER TABLE PROJEKTY ENABLE CONSTRAINT UK_PROJEKTY;

-- Task 11:
ALTER TABLE PROJEKTY MODIFY OPIS_PROJEKTU VARCHAR2(10);

-- Task 12:
DELETE FROM PROJEKTY WHERE OPIS_PROJEKTU='Sieci kręgosłupowe';

-- Task 13:
ALTER TABLE PRZYDZIALY DROP CONSTRAINT FK_PRZYDZIALY_01;
ALTER TABLE PRZYDZIALY ADD CONSTRAINT FK_PRZYDZIALY_01 FOREIGN KEY (ID_PROJEKTU) REFERENCES PROJEKTY(ID_PROJEKTU) ON DELETE CASCADE;

DELETE FROM PROJEKTY WHERE OPIS_PROJEKTU='Sieci kręgosłupowe';

SELECT * FROM PROJEKTY;
SELECT * FROM PRZYDZIALY;

-- Task 14:
DROP TABLE PROJEKTY CASCADE CONSTRAINTS;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE AS C, SEARCH_CONDITION FROM USER_CONSTRAINTS
WHERE TABLE_NAME='PRZYDZIALY' ORDER BY CONSTRAINT_NAME;

-- Task 15:
DROP TABLE PRZYDZIALY;
DROP TABLE PROJEKTY_KOPIA;

SELECT TABLE_NAME FROM USER_TABLES;