-- Task 1:
SELECT * FROM ZESPOLY ORDER BY ID_ZESP ASC;

-- Task 2:
SELECT * FROM PRACOWNICY ORDER BY ID_PRAC ASC;

-- Task 3:
SELECT NAZWISKO, 12*PLACA_POD AS ROCZNA_PLACA FROM PRACOWNICY ORDER BY NAZWISKO ASC;

-- Task 4:
SELECT NAZWISKO, ETAT, PLACA_POD+NVL(PLACA_DOD, 0) AS MIESIECZNE_ZAROBKI FROM PRACOWNICY ORDER BY MIESIECZNE_ZAROBKI DESC;

-- Task 5:
SELECT * FROM ZESPOLY ORDER BY NAZWA ASC;

-- Task 6:
SELECT DISTINCT ETAT FROM PRACOWNICY ORDER BY ETAT ASC;

-- Task 7:
SELECT * FROM PRACOWNICY WHERE ETAT = 'ASYSTENT' ORDER BY NAZWISKO ASC;

-- Task 8:
SELECT ID_PRAC, NAZWISKO, ETAT, PLACA_POD, ID_ZESP FROM PRACOWNICY WHERE ID_ZESP IN(30, 40) ORDER BY PLACA_POD DESC;

-- Task 9:
SELECT NAZWISKO, ID_ZESP, PLACA_POD FROM PRACOWNICY WHERE PLACA_POD BETWEEN 300 AND 800 ORDER BY NAZWISKO ASC;

-- Task 10:
SELECT NAZWISKO, ETAT, ID_ZESP FROM PRACOWNICY WHERE NAZWISKO LIKE '%SKI' ORDER BY NAZWISKO ASC;

-- Task 11:
SELECT ID_PRAC, ID_SZEFA, NAZWISKO, PLACA_POD FROM PRACOWNICY WHERE PLACA_POD > 1000 AND ID_SZEFA IS NOT NULL;

-- Task 12:
SELECT NAZWISKO, ID_ZESP FROM PRACOWNICY WHERE ID_ZESP = 20 AND (NAZWISKO LIKE 'M%' OR NAZWISKO LIKE '%SKI') ORDER BY NAZWISKO ASC;

-- Task 13:
SELECT NAZWISKO, ETAT, PLACA_POD/160 AS STAWKA FROM PRACOWNICY WHERE ETAT NOT IN ('ADIUNKT', 'ASYSTENT', 'STAZYSTA') AND PLACA_POD NOT BETWEEN 400 AND 800 ORDER BY STAWKA ASC;

-- Task 14:
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_DOD FROM PRACOWNICY WHERE PLACA_POD+NVL(PLACA_DOD, 0)>1000 ORDER BY ETAT, NAZWISKO;

-- Task 15:
SELECT NAZWISKO || ' PRACUJE OD ' || ZATRUDNIONY || ' I ZARABIA ' || PLACA_POD AS PROFESOROWIE FROM PRACOWNICY WHERE ETAT='PROFESOR' ORDER BY PLACA_POD DESC;