-- Task 1:
SELECT Z.ID_ZESP, Z.NAZWA, Z.ADRES FROM ZESPOLY Z
WHERE NOT EXISTS (SELECT * FROM PRACOWNICY WHERE ID_ZESP=Z.ID_ZESP);

-- Task 2:
SELECT P.NAZWISKO, P.PLACA_POD, P.ETAT FROM PRACOWNICY P
WHERE PLACA_POD > (SELECT AVG(PLACA_POD) FROM PRACOWNICY HAVING ETAT=P.ETAT GROUP BY ETAT)
ORDER BY P.PLACA_POD DESC;

-- Task 3:
SELECT P.NAZWISKO, P.PLACA_POD FROM PRACOWNICY P
WHERE PLACA_POD>=0.75*(SELECT PLACA_POD FROM PRACOWNICY WHERE ID_PRAC=P.ID_SZEFA);

-- Task 4:
SELECT P.NAZWISKO FROM PRACOWNICY P
WHERE P.ETAT='PROFESOR' AND NOT EXISTS (SELECT * FROM PRACOWNICY WHERE ID_SZEFA=P.ID_PRAC AND ETAT='STAZYSTA');

-- Task 5:
SELECT Z.NAZWA, S1.SUMA AS MAKS_SUMA_PLAC
FROM (SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA FROM PRACOWNICY GROUP BY ID_ZESP) S1
INNER JOIN (SELECT MAX(SUM(PLACA_POD)) AS MAKS_SUMA_PLAC FROM PRACOWNICY GROUP BY ID_ZESP) S2 ON S1.SUMA=S2.MAKS_SUMA_PLAC
INNER JOIN ZESPOLY Z ON Z.ID_ZESP=S1.ID_ZESP;

-- Task 6:
SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY P
WHERE (SELECT COUNT(*) FROM PRACOWNICY WHERE PLACA_POD >= P.PLACA_POD) <= 3;

-- Task 7:
SELECT NAZWISKO, PLACA_POD, PLACA_POD-(SELECT AVG(PLACA_POD) AS ROZNICA FROM PRACOWNICY WHERE ID_ZESP=P.ID_ZESP GROUP BY ID_ZESP)
AS ROZNICA FROM PRACOWNICY P ORDER BY NAZWISKO;

SELECT P.NAZWISKO, P.PLACA_POD, P.PLACA_POD-S1.SREDNIA AS ROZNICA FROM PRACOWNICY P
LEFT OUTER JOIN (SELECT ID_ZESP, AVG(PLACA_POD) AS SREDNIA FROM PRACOWNICY GROUP BY ID_ZESP) S1 ON S1.ID_ZESP = P.ID_ZESP
ORDER BY P.NAZWISKO;

-- Task 8:
SELECT * FROM (SELECT NAZWISKO, PLACA_POD, PLACA_POD-(SELECT AVG(PLACA_POD) AS ROZNICA FROM PRACOWNICY WHERE ID_ZESP=P.ID_ZESP GROUP BY ID_ZESP)  AS ROZNICA FROM PRACOWNICY P)
WHERE ROZNICA > 0
ORDER BY NAZWISKO;

SELECT P.NAZWISKO, P.PLACA_POD, P.PLACA_POD-S1.SREDNIA AS ROZNICA FROM PRACOWNICY P
LEFT OUTER JOIN (SELECT ID_ZESP, AVG(PLACA_POD) AS SREDNIA FROM PRACOWNICY GROUP BY ID_ZESP) S1 ON S1.ID_ZESP = P.ID_ZESP
WHERE P.PLACA_POD-S1.SREDNIA > 0
ORDER BY P.NAZWISKO;

-- Task 9:
SELECT NAZWISKO, (SELECT COUNT(*) FROM PRACOWNICY WHERE ID_SZEFA=P.ID_PRAC GROUP BY ID_SZEFA) AS PODWLADNI FROM PRACOWNICY P
INNER JOIN ZESPOLY Z ON Z.ID_ZESP=P.ID_ZESP
WHERE P.ETAT='PROFESOR' AND UPPER(Z.ADRES) LIKE '%PIOTROWO%';

-- Task 10:
SELECT NAZWA, SREDNIA_W_ZESPOLE, SREDNIA_OGOLNA,CASE 
    WHEN SREDNIA_W_ZESPOLE >= SREDNIA_OGOLNA THEN ':)'
    WHEN SREDNIA_W_ZESPOLE < SREDNIA_OGOLNA THEN ':('
    ELSE '???'
END AS NASTROJE
FROM (SELECT Z.NAZWA, AVG(P.PLACA_POD) AS SREDNIA_W_ZESPOLE, (SELECT ROUND(AVG(PLACA_POD), 2) FROM PRACOWNICY) AS SREDNIA_OGOLNA FROM ZESPOLY Z
LEFT OUTER JOIN PRACOWNICY P ON Z.ID_ZESP=P.ID_ZESP
GROUP BY Z.NAZWA)
ORDER BY NAZWA;

-- Task 11:
SELECT * FROM ETATY E 
ORDER BY (SELECT COUNT('x') FROM PRACOWNICY WHERE E.NAZWA=PRACOWNICY.ETAT) DESC, E.NAZWA;