-- Task 1:
INSERT INTO PRACOWNICY VALUES (250, 'KOWALSKI', 'ASYSTENT', NULL, TO_DATE('2015/01/14', 'yyyy/mm/dd'), 1500, NULL, 10);
INSERT INTO PRACOWNICY VALUES (260, 'ADAMSKI', 'ASYSTENT', NULL, TO_DATE('2014/09/11', 'yyyy/mm/dd'), 1500, NULL, 10);
INSERT INTO PRACOWNICY VALUES (270, 'NOWAK', 'ADIUNKT', NULL, TO_DATE('1990/05/02', 'yyyy/mm/dd'), 2050, 540, 20);

SELECT * FROM PRACOWNICY WHERE ID_PRAC IN (250, 260, 270);

-- Task 2:
UPDATE PRACOWNICY SET
PLACA_POD = 1.1*PLACA_POD,
PLACA_DOD = CASE
WHEN (NVL(PLACA_DOD, 0) = 0) THEN 100
ELSE 1.2*PLACA_DOD
END
WHERE ID_PRAC IN (250, 260, 270);

SELECT * FROM PRACOWNICY WHERE ID_PRAC IN (250, 260, 270);

-- Task 3:
INSERT INTO ZESPOLY VALUES (60, 'BAZY DANYCH', 'PIOTROWO 2');

SELECT * FROM ZESPOLY WHERE ID_ZESP = 60;

-- Task 4:
UPDATE PRACOWNICY SET
ID_ZESP=(SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA='BAZY DANYCH')
WHERE ID_PRAC IN (250, 260, 270);

SELECT * FROM PRACOWNICY WHERE ID_ZESP=(SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA='BAZY DANYCH');

-- Task 5:
UPDATE PRACOWNICY SET
ID_SZEFA=(SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO='MORZY')
WHERE ID_ZESP=(SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA='BAZY DANYCH');

SELECT * FROM PRACOWNICY WHERE ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO='MORZY');

-- Task 6:
DELETE FROM ZESPOLY WHERE NAZWA='BAZY DANYCH';

-- Task 7:
DELETE FROM PRACOWNICY WHERE ID_ZESP = (SELECT ID_ZESP FROM ZESPOLY WHERE NAZWA='BAZY DANYCH') ;
DELETE FROM ZESPOLY WHERE NAZWA='BAZY DANYCH';


-- Task 8:
SELECT P.NAZWISKO, P.PLACA_POD, S.SREDNIA AS PODWYZKA FROM PRACOWNICY P 
INNER JOIN (SELECT ID_ZESP, 0.1*AVG(PLACA_POD) AS SREDNIA FROM PRACOWNICY GROUP BY ID_ZESP) S ON P.ID_ZESP=S.ID_ZESP
ORDER BY P.NAZWISKO;

-- Task 9:
UPDATE PRACOWNICY P SET
P.PLACA_POD=P.PLACA_POD+(SELECT 0.1*AVG(PLACA_POD) AS SREDNIA
FROM PRACOWNICY WHERE ID_ZESP=P.ID_ZESP GROUP BY ID_ZESP);

SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY ORDER BY NAZWISKO;

-- Task 10:
SELECT * FROM PRACOWNICY WHERE PLACA_POD <= ALL(SELECT PLACA_POD FROM PRACOWNICY);

-- Task 11:
UPDATE PRACOWNICY SET
PLACA_POD = (SELECT ROUND(AVG(PLACA_POD), 2) FROM PRACOWNICY)
WHERE PLACA_POD <= ALL(SELECT PLACA_POD FROM PRACOWNICY);

SELECT * FROM PRACOWNICY WHERE ID_PRAC=200;

-- Task 12:
UPDATE PRACOWNICY SET
PLACA_DOD = (SELECT ROUND(AVG(PLACA_POD), 2) FROM PRACOWNICY WHERE ID_SZEFA=(SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO='MORZY'))
WHERE ID_ZESP=20;

SELECT NAZWISKO, PLACA_DOD FROM PRACOWNICY WHERE ID_ZESP=20 ORDER BY NAZWISKO;

-- Task 13:
UPDATE (SELECT NAZWISKO, PLACA_POD, NAZWA FROM PRACOWNICY INNER JOIN ZESPOLY USING (ID_ZESP))
SET PLACA_POD=1.25*PLACA_POD
WHERE NAZWA='SYSTEMY ROZPROSZONE';

SELECT P.NAZWISKO, P.PLACA_POD FROM PRACOWNICY P INNER JOIN ZESPOLY Z ON P.ID_ZESP=Z.ID_ZESP
WHERE Z.NAZWA='SYSTEMY ROZPROSZONE'
ORDER BY P.NAZWISKO;

-- Task 14:
DELETE FROM PRACOWNICY
WHERE ID_SZEFA=(SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO='MORZY');

SELECT * FROM PRACOWNICY WHERE ID_SZEFA=(SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO='MORZY');

-- Task 15:
SELECT * FROM PRACOWNICY ORDER BY NAZWISKO;

-- Task 16:
CREATE SEQUENCE PRAC_SEQ START WITH 300 INCREMENT BY 10;

-- Task 17:
INSERT INTO PRACOWNICY (ID_PRAC, NAZWISKO, ETAT, PLACA_POD)
VALUES (PRAC_SEQ.NEXTVAL, 'Trąbczyński', 'STAZYSTA', 1000);

SELECT * FROM PRACOWNICY WHERE ID_PRAC=300;

-- Task 18:
UPDATE PRACOWNICY SET PLACA_DOD = PRAC_SEQ.CURRVAL
WHERE NAZWISKO = 'Trąbczyński';

SELECT * FROM PRACOWNICY WHERE ID_PRAC=300;

-- Task 19:
DELETE FROM PRACOWNICY
WHERE NAZWISKO = 'Trąbczyński';

-- Task 20:
CREATE SEQUENCE MALA_SEQ START WITH 0 MINVALUE 0 MAXVALUE 5;
SELECT MALA_SEQ.NEXTVAL FROM DUAL;

-- Task 21:
DROP SEQUENCE MALA_SEQ;